tech_data = {
    {
        id = 0x01,
        name = "Cyclone",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x02,
        name = "Slash",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x03,
        name = "Lightning",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "LIGHT",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x04,
        name = "Spincut",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x05,
        name = "Lightning 2",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x06,
        name = "Life",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "DOWN_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "LIFE"
    },
    {
        id = 0x07,
        name = "Confuse",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x08,
        name = "Luminaire",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x09,
        name = "Aura",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x0A,
        name = "Provoke",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "CONFUSE"
    },
    {
        id = 0x0B,
        name = "Ice",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x0C,
        name = "Cure",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x0D,
        name = "Haste",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "SPEED"
    },
    {
        id = 0x0E,
        name = "Cure 2",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x0F,
        name = "Ice 2",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x10,
        name = "Life 2",
        pc1 = "Marle",
        pc2 = "",
        pc3 = "",
        target = "DOWN_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "LIFE"
    },
    {
        id = 0x11,
        name = "Flame Toss",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x12,
        name = "Hypno Wave",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "SLEEP"
    },
    {
        id = 0x13,
        name = "Fire",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x14,
        name = "Napalm",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x15,
        name = "Protect",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "DEF"
    },
    {
        id = 0x16,
        name = "Fire 2",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x17,
        name = "Mega Bomb",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x18,
        name = "Flare",
        pc1 = "Lucca",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x19,
        name = "Rocketpunch",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x1A,
        name = "Cure Beam",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x1B,
        name = "Robo Tackle",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x1C,
        name = "Laser Spin",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x1D,
        name = "Heal Beam",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x1E,
        name = "Uzzi Punch",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x1F,
        name = "Area Bomb",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x20,
        name = "Shock",
        pc1 = "Robo",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x21,
        name = "Slurp",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x22,
        name = "Slurp Cut",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x23,
        name = "Water",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x24,
        name = "Heal",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x25,
        name = "Leap Slash",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x26,
        name = "Water 2",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x27,
        name = "Cure 2",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x28,
        name = "Frog Squash",
        pc1 = "Frog",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x29,
        name = "Kiss",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x2A,
        name = "Rollo Kick",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x2B,
        name = "Cat Attack",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x2C,
        name = "Rock Throw",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x2D,
        name = "Charm",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "STEAL"
    },
    {
        id = 0x2E,
        name = "Triple Kick",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x2F,
        name = "Tailspin",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x30,
        name = "Dino Tail",
        pc1 = "Ayla",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x31,
        name = "Lightning 2",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x32,
        name = "Ice 2",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x33,
        name = "Fire 2",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x34,
        name = "Dark Bomb",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "SHAD",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x35,
        name = "Magic Wall",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ONE_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "DEF"
    },
    {
        id = 0x36,
        name = "Dark Mist",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "SHAD",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x37,
        name = "Black Hole",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "OHKO"
    },
    {
        id = 0x38,
        name = "Dark Matter",
        pc1 = "Magus",
        pc2 = "",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x39,
        name = "Aura Whirl",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x3A,
        name = "Ice Sword",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x3B,
        name = "Ice Sword 2",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x3C,
        name = "Fire Whirl",
        pc1 = "Crono",
        pc2 = "Lucca",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x3D,
        name = "Fire Sword",
        pc1 = "Crono",
        pc2 = "Lucca",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x3E,
        name = "Fire Sword 2",
        pc1 = "Crono",
        pc2 = "Lucca",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x3F,
        name = "Rocket Roll",
        pc1 = "Crono",
        pc2 = "Robo",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x40,
        name = "Max Cyclone",
        pc1 = "Crono",
        pc2 = "Robo",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x41,
        name = "Super Volt",
        pc1 = "Crono",
        pc2 = "Robo",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x42,
        name = "X-strike",
        pc1 = "Crono",
        pc2 = "Frog",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x43,
        name = "Swordstream",
        pc1 = "Crono",
        pc2 = "Frog",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x44,
        name = "Spire",
        pc1 = "Crono",
        pc2 = "Frog",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "LIGHT",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x45,
        name = "Drill Kick",
        pc1 = "Crono",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x46,
        name = "Volt Bite",
        pc1 = "Crono",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "LIGHT",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x47,
        name = "Falcon Hit",
        pc1 = "Crono",
        pc2 = "Ayla",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x48,
        name = "Antipode",
        pc1 = "Marle",
        pc2 = "Lucca",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "WATER",
        type2 = "FIRE",
        type3 = "",
        status = ""
    },
    {
        id = 0x49,
        name = "Antipode 2",
        pc1 = "Marle",
        pc2 = "Lucca",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "WATER",
        type2 = "FIRE",
        type3 = "",
        status = ""
    },
    {
        id = 0x4A,
        name = "Antipode 3",
        pc1 = "Marle",
        pc2 = "Lucca",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "WATER",
        type2 = "FIRE",
        type3 = "",
        status = ""
    },
    {
        id = 0x4B,
        name = "Aura Beam",
        pc1 = "Marle",
        pc2 = "Robo",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x4C,
        name = "Ice Tackle",
        pc1 = "Marle",
        pc2 = "Robo",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x4D,
        name = "Cure Touch",
        pc1 = "Marle",
        pc2 = "Robo",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x4E,
        name = "Ice Water",
        pc1 = "Marle",
        pc2 = "Frog",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x4F,
        name = "Glacier",
        pc1 = "Marle",
        pc2 = "Frog",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x50,
        name = "Double Cure",
        pc1 = "Marle",
        pc2 = "Frog",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x51,
        name = "Twin Charm",
        pc1 = "Marle",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "STEAL"
    },
    {
        id = 0x52,
        name = "Ice Toss",
        pc1 = "Marle",
        pc2 = "Ayla",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x53,
        name = "Cube Toss",
        pc1 = "Marle",
        pc2 = "Ayla",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x54,
        name = "Fire Punch",
        pc1 = "Lucca",
        pc2 = "Robo",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x55,
        name = "Fire Tackle",
        pc1 = "Lucca",
        pc2 = "Robo",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x56,
        name = "Double Bomb",
        pc1 = "Lucca",
        pc2 = "Robo",
        pc3 = "",
        target = "RAD_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x57,
        name = "Red Pin",
        pc1 = "Lucca",
        pc2 = "Frog",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x58,
        name = "Line Bomb",
        pc1 = "Lucca",
        pc2 = "Frog",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x59,
        name = "Frog Flare",
        pc1 = "Lucca",
        pc2 = "Frog",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x5A,
        name = "Flame Kick",
        pc1 = "Lucca",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x5B,
        name = "Blaze Kick",
        pc1 = "Lucca",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "FIRE",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x5C,
        name = "Firewhirl",
        pc1 = "Lucca",
        pc2 = "Ayla",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x5D,
        name = "Blade Toss",
        pc1 = "Robo",
        pc2 = "Frog",
        pc3 = "",
        target = "LINE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x5E,
        name = "Bubble Snap",
        pc1 = "Robo",
        pc2 = "Frog",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x5F,
        name = "Cure Wave",
        pc1 = "Robo",
        pc2 = "Frog",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x60,
        name = "Boogie",
        pc1 = "Robo",
        pc2 = "Ayla",
        pc3 = "",
        target = "ALL_ENEMY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "STOP"
    },
    {
        id = 0x61,
        name = "Spin Kick",
        pc1 = "Robo",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x62,
        name = "Beast Toss",
        pc1 = "Robo",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x63,
        name = "Slurp Kiss",
        pc1 = "Frog",
        pc2 = "Ayla",
        pc3 = "",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x64,
        name = "Bubble Hit",
        pc1 = "Frog",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "WATER",
        type2 = "PHYS",
        type3 = "",
        status = ""
    },
    {
        id = 0x65,
        name = "Drop Kick",
        pc1 = "Frog",
        pc2 = "Ayla",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x66,
        name = "Delta Force",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "Lucca",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "WATER",
        type3 = "FIRE",
        status = ""
    },
    {
        id = 0x67,
        name = "Life Line",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "Robo",
        target = "ALL_ALLY",
        type1 = "STAT",
        type2 = "",
        type3 = "",
        status = "HEAL"
    },
    {
        id = 0x68,
        name = "Arc Impulse",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "Frog",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "WATER",
        type3 = "",
        status = ""
    },
    {
        id = 0x69,
        name = "Gatling Kick",
        pc1 = "Crono",
        pc2 = "Lucca",
        pc3 = "Ayla",
        target = "ONE_ENEMY",
        type1 = "LIGHT",
        type2 = "FIRE",
        type3 = "PHYS",
        status = ""
    },
    {
        id = 0x6A,
        name = "Fire Circle",
        pc1 = "Crono",
        pc2 = "Lucca",
        pc3 = "Robo",
        target = "ALL_ENEMY",
        type1 = "FIRE",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x6B,
        name = "Delta Storm",
        pc1 = "Crono",
        pc2 = "Lucca",
        pc3 = "Frog",
        target = "ALL_ENEMY",
        type1 = "LIGHT",
        type2 = "FIRE",
        type3 = "WATER",
        status = ""
    },
    {
        id = 0x6C,
        name = "Final Kick",
        pc1 = "Crono",
        pc2 = "Marle",
        pc3 = "Ayla",
        target = "ONE_ENEMY",
        type1 = "LIGHT",
        type2 = "WATER",
        type3 = "PHYS",
        status = ""
    },
    {
        id = 0x6D,
        name = "Triple Raid",
        pc1 = "Crono",
        pc2 = "Frog",
        pc3 = "Robo",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x6E,
        name = "Twister",
        pc1 = "Crono",
        pc2 = "Robo",
        pc3 = "Ayla",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x6F,
        name = "3D Attack",
        pc1 = "Crono",
        pc2 = "Frog",
        pc3 = "Ayla",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x70,
        name = "Dark Eternal",
        pc1 = "Marle",
        pc2 = "Lucca",
        pc3 = "Magus",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "WATER",
        type3 = "FIRE",
        status = ""
    },
    {
        id = 0x71,
        name = "Omega Flare",
        pc1 = "Lucca",
        pc2 = "Robo",
        pc3 = "Magus",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "FIRE",
        type3 = "LIGHT",
        status = ""
    },
    {
        id = 0x72,
        name = "Spin Strike",
        pc1 = "Robo",
        pc2 = "Frog",
        pc3 = "Ayla",
        target = "ONE_ENEMY",
        type1 = "PHYS",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x73,
        name = "Poyozo Dance",
        pc1 = "Marle",
        pc2 = "Lucca",
        pc3 = "Ayla",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x74,
        name = "Grand Dream",
        pc1 = "Marle",
        pc2 = "Robo",
        pc3 = "Frog",
        target = "ALL_ENEMY",
        type1 = "SHAD",
        type2 = "WATER",
        type3 = "",
        status = ""
    },
    {
        id = 0x75,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x76,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x77,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x78,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x79,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x7A,
        name = "Angel Attack",
        pc1 = "Crono",
        pc2 = "",
        pc3 = "",
        target = "ONE_ENEMY",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x7B,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x7C,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x7D,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x7E,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    },
    {
        id = 0x7F,
        name = "[none]",
        pc1 = "",
        pc2 = "",
        pc3 = "",
        target = "",
        type1 = "",
        type2 = "",
        type3 = "",
        status = ""
    }
}
